// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: shape.proto

package shape

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShapeInfo_QuantityType int32

const (
	ShapeInfo_UNKNOWN_QUANTITY ShapeInfo_QuantityType = 0
	ShapeInfo_AREA             ShapeInfo_QuantityType = 1
	ShapeInfo_VOLUME           ShapeInfo_QuantityType = 2
	ShapeInfo_PERIMETER        ShapeInfo_QuantityType = 3
)

// Enum value maps for ShapeInfo_QuantityType.
var (
	ShapeInfo_QuantityType_name = map[int32]string{
		0: "UNKNOWN_QUANTITY",
		1: "AREA",
		2: "VOLUME",
		3: "PERIMETER",
	}
	ShapeInfo_QuantityType_value = map[string]int32{
		"UNKNOWN_QUANTITY": 0,
		"AREA":             1,
		"VOLUME":           2,
		"PERIMETER":        3,
	}
)

func (x ShapeInfo_QuantityType) Enum() *ShapeInfo_QuantityType {
	p := new(ShapeInfo_QuantityType)
	*p = x
	return p
}

func (x ShapeInfo_QuantityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShapeInfo_QuantityType) Descriptor() protoreflect.EnumDescriptor {
	return file_shape_proto_enumTypes[0].Descriptor()
}

func (ShapeInfo_QuantityType) Type() protoreflect.EnumType {
	return &file_shape_proto_enumTypes[0]
}

func (x ShapeInfo_QuantityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShapeInfo_QuantityType.Descriptor instead.
func (ShapeInfo_QuantityType) EnumDescriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{0, 0}
}

type ShapeInfo_ShapeType int32

const (
	ShapeInfo_UNKNOWN_SHAPE ShapeInfo_ShapeType = 0
	ShapeInfo_RECTANGLE     ShapeInfo_ShapeType = 1
	ShapeInfo_CUBE          ShapeInfo_ShapeType = 2
)

// Enum value maps for ShapeInfo_ShapeType.
var (
	ShapeInfo_ShapeType_name = map[int32]string{
		0: "UNKNOWN_SHAPE",
		1: "RECTANGLE",
		2: "CUBE",
	}
	ShapeInfo_ShapeType_value = map[string]int32{
		"UNKNOWN_SHAPE": 0,
		"RECTANGLE":     1,
		"CUBE":          2,
	}
)

func (x ShapeInfo_ShapeType) Enum() *ShapeInfo_ShapeType {
	p := new(ShapeInfo_ShapeType)
	*p = x
	return p
}

func (x ShapeInfo_ShapeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShapeInfo_ShapeType) Descriptor() protoreflect.EnumDescriptor {
	return file_shape_proto_enumTypes[1].Descriptor()
}

func (ShapeInfo_ShapeType) Type() protoreflect.EnumType {
	return &file_shape_proto_enumTypes[1]
}

func (x ShapeInfo_ShapeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShapeInfo_ShapeType.Descriptor instead.
func (ShapeInfo_ShapeType) EnumDescriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{0, 1}
}

type ShapeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          *Identifier             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shape       ShapeInfo_ShapeType     `protobuf:"varint,2,opt,name=shape,proto3,enum=shape.ShapeInfo_ShapeType" json:"shape,omitempty"`
	Mesurements []*ShapeInfo_Mesurement `protobuf:"bytes,3,rep,name=mesurements,proto3" json:"mesurements,omitempty"`
	Timestamp   *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *ShapeInfo) Reset() {
	*x = ShapeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeInfo) ProtoMessage() {}

func (x *ShapeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_shape_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeInfo.ProtoReflect.Descriptor instead.
func (*ShapeInfo) Descriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{0}
}

func (x *ShapeInfo) GetId() *Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ShapeInfo) GetShape() ShapeInfo_ShapeType {
	if x != nil {
		return x.Shape
	}
	return ShapeInfo_UNKNOWN_SHAPE
}

func (x *ShapeInfo) GetMesurements() []*ShapeInfo_Mesurement {
	if x != nil {
		return x.Mesurements
	}
	return nil
}

func (x *ShapeInfo) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Cuboid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Length int64       `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Width  int64       `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height int64       `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *Cuboid) Reset() {
	*x = Cuboid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cuboid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cuboid) ProtoMessage() {}

func (x *Cuboid) ProtoReflect() protoreflect.Message {
	mi := &file_shape_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cuboid.ProtoReflect.Descriptor instead.
func (*Cuboid) Descriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{1}
}

func (x *Cuboid) GetId() *Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Cuboid) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Cuboid) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Cuboid) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Rectangle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     *Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Length int64       `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Width  int64       `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *Rectangle) Reset() {
	*x = Rectangle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rectangle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rectangle) ProtoMessage() {}

func (x *Rectangle) ProtoReflect() protoreflect.Message {
	mi := &file_shape_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rectangle.ProtoReflect.Descriptor instead.
func (*Rectangle) Descriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{2}
}

func (x *Rectangle) GetId() *Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Rectangle) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Rectangle) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

type Identifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // unique ID of a shape
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // name of the shape, can be null or empty, doesn't need to be unique
}

func (x *Identifier) Reset() {
	*x = Identifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Identifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identifier) ProtoMessage() {}

func (x *Identifier) ProtoReflect() protoreflect.Message {
	mi := &file_shape_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identifier.ProtoReflect.Descriptor instead.
func (*Identifier) Descriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{3}
}

func (x *Identifier) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Identifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlanarCoordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *Identifier         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Shape ShapeInfo_ShapeType `protobuf:"varint,2,opt,name=shape,proto3,enum=shape.ShapeInfo_ShapeType" json:"shape,omitempty"`
	X     int64               `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"` // length is x-axis
	Y     int64               `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"` // width is y-axis
	Z     int64               `protobuf:"varint,5,opt,name=z,proto3" json:"z,omitempty"` // height is z-axis
}

func (x *PlanarCoordinates) Reset() {
	*x = PlanarCoordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlanarCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanarCoordinates) ProtoMessage() {}

func (x *PlanarCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_shape_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanarCoordinates.ProtoReflect.Descriptor instead.
func (*PlanarCoordinates) Descriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{4}
}

func (x *PlanarCoordinates) GetId() *Identifier {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PlanarCoordinates) GetShape() ShapeInfo_ShapeType {
	if x != nil {
		return x.Shape
	}
	return ShapeInfo_UNKNOWN_SHAPE
}

func (x *PlanarCoordinates) GetX() int64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlanarCoordinates) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlanarCoordinates) GetZ() int64 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ShapeInfo_Mesurement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  ShapeInfo_QuantityType `protobuf:"varint,1,opt,name=name,proto3,enum=shape.ShapeInfo_QuantityType" json:"name,omitempty"`
	Value float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ShapeInfo_Mesurement) Reset() {
	*x = ShapeInfo_Mesurement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shape_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShapeInfo_Mesurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShapeInfo_Mesurement) ProtoMessage() {}

func (x *ShapeInfo_Mesurement) ProtoReflect() protoreflect.Message {
	mi := &file_shape_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShapeInfo_Mesurement.ProtoReflect.Descriptor instead.
func (*ShapeInfo_Mesurement) Descriptor() ([]byte, []int) {
	return file_shape_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ShapeInfo_Mesurement) GetName() ShapeInfo_QuantityType {
	if x != nil {
		return x.Name
	}
	return ShapeInfo_UNKNOWN_QUANTITY
}

func (x *ShapeInfo_Mesurement) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_shape_proto protoreflect.FileDescriptor

var file_shape_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x68, 0x61, 0x70, 0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb4, 0x03, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x70, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x53, 0x68,
	0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x6d, 0x65, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x4d, 0x65, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x75,
	0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x1a, 0x55, 0x0a, 0x0a, 0x4d, 0x65, 0x73, 0x75, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x31, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e,
	0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e,
	0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x49, 0x0a, 0x0c, 0x51, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e, 0x4b, 0x4e,
	0x4f, 0x57, 0x4e, 0x5f, 0x51, 0x55, 0x41, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x41, 0x52, 0x45, 0x41, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x56, 0x4f, 0x4c, 0x55,
	0x4d, 0x45, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x45, 0x52, 0x49, 0x4d, 0x45, 0x54, 0x45,
	0x52, 0x10, 0x03, 0x22, 0x37, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x70, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x53, 0x48, 0x41, 0x50,
	0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x45, 0x43, 0x54, 0x41, 0x4e, 0x47, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x55, 0x42, 0x45, 0x10, 0x02, 0x22, 0x71, 0x0a, 0x06,
	0x43, 0x75, 0x62, 0x6f, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e,
	0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74,
	0x68, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x5c, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65,
	0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x22, 0x30, 0x0a,
	0x0a, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x92, 0x01, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x6e, 0x61, 0x72, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e, 0x73, 0x68, 0x61, 0x70, 0x65, 0x2e,
	0x53, 0x68, 0x61, 0x70, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x68, 0x61, 0x70, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x01, 0x7a, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6d, 0x75, 0x7a, 0x61, 0x6d, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x65, 0x74,
	0x72, 0x79, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73,
	0x68, 0x61, 0x70, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shape_proto_rawDescOnce sync.Once
	file_shape_proto_rawDescData = file_shape_proto_rawDesc
)

func file_shape_proto_rawDescGZIP() []byte {
	file_shape_proto_rawDescOnce.Do(func() {
		file_shape_proto_rawDescData = protoimpl.X.CompressGZIP(file_shape_proto_rawDescData)
	})
	return file_shape_proto_rawDescData
}

var file_shape_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_shape_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shape_proto_goTypes = []interface{}{
	(ShapeInfo_QuantityType)(0),   // 0: shape.ShapeInfo.QuantityType
	(ShapeInfo_ShapeType)(0),      // 1: shape.ShapeInfo.ShapeType
	(*ShapeInfo)(nil),             // 2: shape.ShapeInfo
	(*Cuboid)(nil),                // 3: shape.Cuboid
	(*Rectangle)(nil),             // 4: shape.Rectangle
	(*Identifier)(nil),            // 5: shape.Identifier
	(*PlanarCoordinates)(nil),     // 6: shape.PlanarCoordinates
	(*ShapeInfo_Mesurement)(nil),  // 7: shape.ShapeInfo.Mesurement
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_shape_proto_depIdxs = []int32{
	5, // 0: shape.ShapeInfo.id:type_name -> shape.Identifier
	1, // 1: shape.ShapeInfo.shape:type_name -> shape.ShapeInfo.ShapeType
	7, // 2: shape.ShapeInfo.mesurements:type_name -> shape.ShapeInfo.Mesurement
	8, // 3: shape.ShapeInfo.timestamp:type_name -> google.protobuf.Timestamp
	5, // 4: shape.Cuboid.id:type_name -> shape.Identifier
	5, // 5: shape.Rectangle.id:type_name -> shape.Identifier
	5, // 6: shape.PlanarCoordinates.id:type_name -> shape.Identifier
	1, // 7: shape.PlanarCoordinates.shape:type_name -> shape.ShapeInfo.ShapeType
	0, // 8: shape.ShapeInfo.Mesurement.name:type_name -> shape.ShapeInfo.QuantityType
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_shape_proto_init() }
func file_shape_proto_init() {
	if File_shape_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shape_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShapeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Cuboid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rectangle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Identifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlanarCoordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shape_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShapeInfo_Mesurement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shape_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shape_proto_goTypes,
		DependencyIndexes: file_shape_proto_depIdxs,
		EnumInfos:         file_shape_proto_enumTypes,
		MessageInfos:      file_shape_proto_msgTypes,
	}.Build()
	File_shape_proto = out.File
	file_shape_proto_rawDesc = nil
	file_shape_proto_goTypes = nil
	file_shape_proto_depIdxs = nil
}
